drop table NEWR_REPOS.PARTICIPANT_CORE_BALANCE;
drop table NEWR_REPOS.PARTICIPANT_CORE_BALANCE_delta;
drop table NEWR_REPOS.PARTICIPANT_CORE_BALANCE_monthly;
drop table NEWR_REPOS.PARTICIPANT_CORE_BALANCE_monthly_delta;
drop table NEWR_REPOS.plan;
drop table NEWR_REPOS.plan_delta;
drop table NEWR_REPOS.txn;
drop table NEWR_REPOS.txn_delta;
drop table NEWR_REPOS.PARTICIPANT;
drop table NEWR_REPOS.PARTICIPANT_DELTA;

---txn

CREATE TABLE NEWR_REPOS.TXN
( 
  CLIENT_ID VARCHAR2(10 BYTE)  
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, TRADE_DATE DATE NOT NULL 
, RUN_DATE DATE NOT NULL 
, RUN_TIME VARCHAR2(20 BYTE) NOT NULL
, BASE_TRANSACTION_CODE VARCHAR2(20 BYTE) NOT NULL 
, ACTIVITY_TYPE NUMBER(32, 0) NOT NULL 
, REV_CODE VARCHAR2(20 BYTE) NOT NULL  
, FUND_IV VARCHAR2(20 BYTE) 
, FUND_NUMBER VARCHAR2(15 BYTE) 
, FUND_SRC VARCHAR2(20 BYTE) 
, MONEY_SOURCE VARCHAR2(10 BYTE) 
, CASH NUMBER(13, 2) 
, UNINVESTED_CASH NUMBER(13, 2) 
, SHARES NUMBER(13, 4) 
, SHARE_PRICE NUMBER(13, 6) 
, SEQUENCE_NUMBER VARCHAR2(50 BYTE) NOT NULL 
, POSTING_PROCESS_COUNTER VARCHAR2(20 BYTE) NOT NULL 
, USAGE_CODE_1 VARCHAR2(20 BYTE) 
, USAGE_CODE_2 VARCHAR2(20 BYTE) 
, USAGE_CODE_3 VARCHAR2(20 BYTE) 
, USAGE_CODE_4 VARCHAR2(20 BYTE) 
, USAGE_CODE_5 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_1 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_2 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_3 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_4 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_5 VARCHAR2(20 BYTE) 
, PREVIOUS_ACTIVITY_DATE DATE 
, CATEGORY VARCHAR2(100 BYTE) 
, OTHER_CASH NUMBER(13, 2)
, ACTIVITY VARCHAR2(30 BYTE) 
, NET_CURRENCY_VALUE NUMBER(13, 2) 
, ALT_POSTING_PROCESS_COUNTER NUMBER(38, 0) 
, ASSOCIATED_ACTIVITY NUMBER(38, 0)  
, PAY_PERIOD_END_DATE DATE 
, REC_CODE VARCHAR2(20 BYTE) 
, RECORD_TYPE VARCHAR2(20 BYTE) 
, RESERVED_CASH_SHARES_IND NUMBER(15, 2)
, REVERSAL_REASON VARCHAR2(20 BYTE) 
, REVERSE_RUN_DATE DATE 
, SHARE_CLASS VARCHAR2(20 BYTE)
, SHARE_COST NUMBER(13, 2)
, TRAN_SEQ NUMBER(32, 0) 
, VOUCHER_NUMBER NUMBER(38, 0) 
, REC_TYPE VARCHAR2(6 BYTE) 
, ETIN_NUM VARCHAR2(9 BYTE) 
, FILEID_EXT VARCHAR2(20 BYTE) 
, FILEID_NAME VARCHAR2(20 BYTE) 
, FILEID_PTR_INDIC VARCHAR2(20 BYTE) 
, MARGIN_CODE VARCHAR2(10 BYTE)
, PART_EXT VARCHAR2(20 BYTE) 
, PART_EXT1 VARCHAR2(20 BYTE) 
, PART_NUM_X VARCHAR2(9 BYTE) 
, PART_NUM NUMBER(32, 0) 
, PART_SUB_PLAN VARCHAR2(6 BYTE) 
, PEND_STAT VARCHAR2(20 BYTE)
, PLAN_NUM VARCHAR2(6 BYTE)
, SEPARATE_ACCT VARCHAR2(20 BYTE) 
, COMPANY_CODE VARCHAR2(20 BYTE)  
, CURRENCY_CODE VARCHAR2(5 BYTE)
, CURRENCY_VALUE NUMBER(13, 2)
, SUB_ACTIVITY_CODE NUMBER(38, 0) 
, SOURCE_CYCLE_DATE DATE 
, TRADE_TYPE VARCHAR2(10 BYTE)
, SOURCE_PROCESSING_DATE DATE 
, TRAN_CODE VARCHAR2(20 BYTE) 
, SOURCE_SYSTEM VARCHAR2(40 BYTE) 
, USE_PLAN_YEAR_FLAG VARCHAR2(10 BYTE) 
, XR_RATE NUMBER(11, 6)  
, XR_TYPE VARCHAR2(20 BYTE) 
, PLAN_SEQUENCE VARCHAR2(6 BYTE)
, ACTIVITY_CODE_DESCRIPTION VARCHAR2(255)
, SEQ_OPER_CODE VARCHAR2(20 BYTE) ,
 record_Keeping_group_ind  VARCHAR2(20 BYTE) ,
, TRANSFORM_HASH_KEY NUMBER(38, 0) ,
CONSTRAINT PK_TXN PRIMARY KEY 
(
  ACTIVITY_TYPE 
, BASE_TRANSACTION_CODE 
, POSTING_PROCESS_COUNTER 
, REV_CODE 
, RUN_DATE 
, RUN_TIME 
, SEQUENCE_NUMBER 
, TRADE_DATE 
, PARTICIPANT_ID 
, PLAN_NUMBER 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;
--participant

CREATE TABLE NEWR_REPOS.PARTICIPANT
( 
 CLIENT_ID VARCHAR2(10 BYTE) NOT NULL 
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, DIV_SUB_ID VARCHAR2(25 BYTE) 
, RETIREMENT_ACCOUNT_ID VARCHAR2(27 BYTE) NOT NULL 
, CUST_ODS_AGREEMENT_ID VARCHAR2(36 BYTE) 
, FIRST_NAME VARCHAR2(255 BYTE) 
, MIDDLE_NAME VARCHAR2(255 BYTE)
, LAST_NAME VARCHAR2(255 BYTE) 
, NAME_SUFFIX VARCHAR2(4 BYTE) 
, NAME_FORMATTED VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_1 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_2 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_3 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_4 VARCHAR2(255 BYTE)
, PART_ADDRESS_CITY VARCHAR2(255 BYTE)  
, PART_ADDRESS_STATE VARCHAR2(100 BYTE) 
, PART_ADDRESS_ZIP_CODE VARCHAR2(20 BYTE)
, BIRTH_DATE DATE
, AGE NUMBER(38, 0) 
, ATTAINED_AGE NUMBER(7, 2) 
, GENDER_CODE VARCHAR2(10 BYTE)
, GENDER_DESC VARCHAR2(55 BYTE) 
, EMAIL_ADDRESS VARCHAR2(255 BYTE) 
, MARITAL_STATUS_CODE VARCHAR2(5 BYTE)
, MARITAL_STATUS_CODE_DESC VARCHAR2(40 BYTE) 
, PART_PRODUCT_ID VARCHAR2(6 BYTE) 
, PRODUCT_CODE VARCHAR2(2 BYTE)
, PRODUCT_NAME VARCHAR2(20 BYTE) 
, PLAN_CODE VARCHAR2(6 BYTE) 
, PARTICIPANT_STATUS_CODE VARCHAR2(20 BYTE) 
, PART_STATUS_DESC VARCHAR2(10 BYTE) 
, PART_ACCT_STATUS_DATE DATE  
, CLIENT_STATUS VARCHAR2(10 BYTE)
, ACCOUNT_INCEPTION_DATE DATE 
, PLAN_ENTRY_DATE DATE 
, REINSTATEMENT_NOTIFY_DATE DATE 
, QDIA_DATE DATE 
, ENROLLMENT_DATE DATE 
, EMPLOYMENT_DATE DATE 
, ELIGIBLE_FOR_DISTRIBUTION_DATE DATE 
, ELIGIBILITY_REMINDER_DATE DATE 
, ELIGIBILITY_DATE DATE 
, ELIGIBILITY_COMPLETION_DATE DATE 
, ELIGIBILITY_5500_DATE DATE 
, DOLLAR5000_REACHED_DATE DATE 
, DEMOGRAPHIC_EFFECTIVE_DATE DATE 
, AUTO_ENROLLMENT_DATE DATE 
, ALTERNATE_VESTING_DATE DATE 
, TERMINATION_NOTIFICATION_DATE DATE 
, TERMINATION_DATE DATE 
, SUSPENSION_DATE DATE 
, LEAVE_OF_ABSENSE_END_DATE DATE 
, DEFER_DATE DATE
, DEATH_DATE DATE 
, SPOUSE_CONSENT_EXPIRATION_DATE DATE 
, ROTH_FIRST_CONTRIBUTION_DATE DATE  
, FE_START_DATE DATE 
, FE_END_DATE DATE
, NEXT_REBALANCE_DATE DATE 
, MVA_CHARGED_TO_DATE DATE 
, MIN_DISTRIB_ELIGIBILITY_DATE DATE 
, MIN_DISTRIB_BEGIN_DATE_OPTION VARCHAR2(1 BYTE) 
, LAST_TRANSFER_DATE DATE 
, LAST_PLAN_TO_PLAN_TRANSF_DATE DATE 
, LAST_LOAN_DEFAULT_DATE DATE 
, LAST_HARDSHIP_WITHDRAWAL_DATE DATE 
, LAST_CONTRIBUTION_DATE DATE 
, LAST_CONTRIB_RATE_CHANGE_DATE DATE 
, LAST_ALLOC_PCT_CHANGE_DATE DATE 
, INIT_ROLLOVER_DIST_DATE DATE 
, INIT_PARTIAL_TERM_DIST_DATE DATE 
, FREE_LOOK_END_DATE DATE 
, FIRST_DEFAULT_CONTRIB_DATE DATE 
, FIRST_CONTRIBUTION_DATE DATE 
, EXCESS_TRADER_SUSPEND_END_DATE DATE 
, EXCESS_TRADER_SUSP_START_DATE DATE  
, HIGHEST_OUTSTAND_LOAN_BALANCE NUMBER(11, 2) 
, SPOUSE_BIRTH_DATE DATE 
, SPOUSE_NAME VARCHAR2(255 BYTE) 
, YTD_CONTRIBUTIONS NUMBER(15, 2) 
, AUTO_ENROLLMENT_INDICATOR VARCHAR2(10 BYTE) 
, TOTAL_NUMBER_OF_FUNDS NUMBER(38, 0) 
, TERMINATION_REASON_CODE VARCHAR2(2 BYTE) 
, TERM_STAT_REASON_CODE VARCHAR2(2 BYTE) 
, SUSPENSION_MONTHS_FORF_REALLOC NUMBER(38, 0)
, SUSPENSION_MONTHS_ER_CONTRIB NUMBER(38, 0) 
, SUSPENSION_MONTHS_EE_CONTRIB NUMBER(38, 0) 
, PART_SSN VARCHAR2(17 BYTE) 
, PART_SSN_LAST_4 VARCHAR2(4 BYTE) 
, QDRO_FLAG VARCHAR2(1 BYTE) 
, QDRO_STATUS VARCHAR2(1 BYTE) 
, QDRO_BENEFICARY_SSN NUMBER(11, 2) 
, QDIA_INDICATOR VARCHAR2(1 BYTE)
, DEFAULT_ENROLLED_QDIA VARCHAR2(1 BYTE) 
, ROTH_UNRESTRICTED_CONTRIB NUMBER(11, 2) 
, ROTH_SMA_ACCOUNT_NUMBER VARCHAR2(254 BYTE) 
, ROTH_IPRR_CONTRIBUTIONS NUMBER(11, 2) 
, ROTH_YEAR VARCHAR2(4 BYTE) 
, ROTH_DEFERRAL_CONTRIBUTIONS NUMBER(11, 2) 
, ROLL_CONTRIBUTION_PRIOR_YEAR NUMBER(11, 2) 
, ROLL_CONTRIBUTION_CURRENT_YEAR NUMBER(11, 2) 
, ROLL_ACCOUNT_TYPE VARCHAR2(1 BYTE)
, PRE1987_EE_AFTERTAX_CONTRIB NUMBER(11, 2) 
, PRE_TAX_401K_CONTRIB_PRIOR NUMBER(11, 2) 
, PRE_TAX_401K_CONTRIB_CURRENT NUMBER(11, 2)
, POST1986_EE_AFTERTAX_CONTRIB NUMBER(11, 2) 
, POST88_SURENDER VARCHAR2(15 BYTE) 
, PLAN_YEAR_COMPENSATION_PRIOR NUMBER(15, 2) 
, PLAN_YEAR_COMPENSATION_CURRENT NUMBER(15, 2) 
, NONQUAL_IND VARCHAR2(10 BYTE) 
, EE_CONTRIB_TAXED_BY_STATE NUMBER(38, 0)
, EE_CONTRIB_401K_STATE_TAX_FLAG VARCHAR2(1 BYTE) 
, EE_CONTRIB_401K_PRIOR_YEAR NUMBER(11, 2) 
, EE_CONTRIB_401K_CURRENT_YEAR NUMBER(11, 2) 
, EE_CONTRIB_YTD NUMBER(7, 2) 
, ee_contrib_prior_tax_year NUMBER(7, 2) 
, DIVIDEND_PASS_THRU_INDICATOR NUMBER(4, 1) 
, DIVIDEND_PASS_THRU_ELECTION NUMBER(5, 4) 
, DIVIDEND_PASS_THRU_ELECTION_PCT NUMBER(4, 1)  
, CONTRIBUTION_415_PRIOR NUMBER(11, 2) 
, CONTRIBUTION_415_CURRENT NUMBER(11, 2) 
, EMPLOYEE_ID VARCHAR2(13 BYTE) 
, EMPLOYEE_NUMBER VARCHAR2(40 BYTE) 
, EMPLOYEE_NUMBER_2 VARCHAR2(40 BYTE) 
, EMPLOYMENT_STATUS_REASON VARCHAR2(1 BYTE) 
, KEY_EMPLOYEE_INDICATOR VARCHAR2(1 BYTE)
, RELATED_PARTICIPANT_ID VARCHAR2(25 BYTE) 
, SMA_FUND_BALANCE NUMBER(15, 2) 
, SDBO_HOLD_HARMLESS VARCHAR2(1 BYTE) 
, FINANCIAL_ENGINS_PROSPECT_CODE VARCHAR2(1 BYTE) 
, WITHDRAWAL_RESTRICTION_REASON VARCHAR2(1 BYTE) 
, WITHDRAWAL_RESTRICTION VARCHAR2(1 BYTE) 
, VERY_IMPORTANT_PERSON_INDICAT VARCHAR2(254 BYTE) 
, TRADE_ACTIVITY VARCHAR2(2 BYTE) 
, TAX_TREATY_COUNTRY_CODE VARCHAR2(3 BYTE) 
, SOURCE_ADJ_VEST_PERCENT NUMBER(4, 3) 
, REDUCTION_401K_OPTION VARCHAR2(254 BYTE) 
, PUERTO_RICO_RESIDENT VARCHAR2(3 BYTE) 
, PRIOR_HCE_INDICATOR VARCHAR2(1 BYTE) 
, PLAN_REFERENCE_KEY VARCHAR2(8 BYTE) 
, PERIODS_OF_CONTINUOUS_SERVICE NUMBER(38, 0) 
, PAYROLL_FREQUENCY VARCHAR2(1 BYTE) 
, PAY_GROUP_ID VARCHAR2(5 BYTE) 
, PERSON_FLAG VARCHAR2(1 BYTE) 
, INSTALLMENT_STATUS VARCHAR2(10 BYTE) 
, HCE_STATUS VARCHAR2(10 BYTE) 
, CATCHUP_ELIGIBLE_FLAG VARCHAR2(1 BYTE) 
, ACCOUNT_TYPE_CODE_DESC VARCHAR2(40 BYTE) 
, ACCOUNT_TYPE_CODE VARCHAR2(30 BYTE) 
, ACCOUNT_TYPE VARCHAR2(55 BYTE)
, STATUS_16B VARCHAR2(10 BYTE) 
, YTD_HOURS_WORKED VARCHAR2(10 BYTE) 
, PHONE VARCHAR2(32 BYTE) 
, PART_PERSON_FLAG VARCHAR2(1 BYTE)
, PAYROLL_LOCATION VARCHAR2(5 BYTE)  
, LOCATION_CODE VARCHAR2(4 BYTE)  
, LINE_OF_BUSINESS VARCHAR2(3 BYTE) 
, AGG_SYS_KEY VARCHAR2(24 BYTE)  
, WITHHOLDING_PCT_OVERRIDE NUMBER(5, 4) 
, WITHHOLDING_AMOUNT_OVERRIDE NUMBER(11, 2) 
, WITHHOLDING_OVERRIDE VARCHAR2(1 BYTE)
, ORACLE_PLAN_RULE_ID VARCHAR2(80 BYTE) 
, OLD_ADVICE_ACCOUNT VARCHAR2(80 BYTE) 
, NET_401K_ELECTIVE_DEFERRALS NUMBER(11, 2) 
, MIN_DISTRIB_SUPPRESS_OPTION VARCHAR2(1 BYTE) 
, MIN_DISTRIB_CALCULATION_METHOD VARCHAR2(1 BYTE)
, MATCH_PAYROLL_GENERIC_GROUPING VARCHAR2(5 BYTE) 
, MANAGED_ACCT_SALARY_AT_ENROLL NUMBER(11, 2) 
, LIFETIME_DSC_AMOUNT NUMBER(11, 2)
, LAST_CONTRIBUTION_AMT_GROSS NUMBER(17, 2)
, LANGUAGE_PRINT_PREFERENCE VARCHAR2(3 BYTE) 
, INSIDE_TRADING_16B_RESTRICT_ID VARCHAR2(1 BYTE)  
, ILIP_EQUITY_WASH_RESIDUAL_AMT NUMBER(11, 2) 
, HUMAN_RESOURCE_STATUS_CODE VARCHAR2(10 BYTE) 
, HOURS_OF_SERVICE NUMBER(38, 0) 
, HIGHLY_COMPENSATED_EE_FLAG VARCHAR2(1 BYTE) 
, HIGH_LOAN_BALANCE_AMOUNT NUMBER(11, 2) 
, HCE_INDICATOR VARCHAR2(1 BYTE) 
, GROUP_PAYMENT_STATUS_FLAG VARCHAR2(1 BYTE) 
, GROUP_IV_ID VARCHAR2(2 BYTE) 
, FOREIGN_COUNTRY_CODE VARCHAR2(3 BYTE)
, FLAG_16B VARCHAR2(1 BYTE) 
, FEDERAL_W4P_FORM_STATUS VARCHAR2(1 BYTE)
, EXCESS_TRADER_SUSPEND_FLAG VARCHAR2(1 BYTE) 
, ESOP_DIVERSIFICATION_SHARES NUMBER(11, 2) 
, ER_AFTER_TAX_AMOUNT NUMBER(11, 2) 
, EQUITY_WASH_AMOUNT NUMBER(11, 2) 
, ELIGIBLE_FOR_BONUS VARCHAR2(1 BYTE) 
, ELIGIBILITY_EXCLUSION VARCHAR2(1 BYTE) 
, ELIG_ROLLOVER_DISTRIBUTIONS NUMBER(11, 2) 
, EGTRRA_TARGET_MESSAGE_ID NUMBER(38, 0) 
, DEFERRAL_GROUPING_ID VARCHAR2(4 BYTE) 
, DEFAULT_INVESTMENT_FLAG VARCHAR2(20 BYTE)  
, DEFAULT_DEFERRAL_FLAG VARCHAR2(20 BYTE)
, DEATH_BENEFIT_PERCENTAGE NUMBER(38, 0)
, STATE_CONTRIB_TAXED_BY_FLAG VARCHAR2(1 BYTE) 
, CLIENT_PASS_THRU_IDENTIFIER VARCHAR2(10 BYTE) 
, BROKERAGE_ACCOUNT_NUMBER VARCHAR2(20 BYTE)
, BENEFICIARY_CODE VARCHAR2(1 BYTE) 
, AUTOMATIC_INCREASE_FLAG VARCHAR2(1 BYTE) 
, ANNUAL_SALARY NUMBER(11, 2) 
, ANNUAL_DIST_AMOUNT NUMBER(11, 2) 
, ALTERNATE_TAXABILITY_STATE VARCHAR2(2 BYTE) 
, ALTERNATE_ACCOUNT_NUMBER VARCHAR2(100 BYTE) 
, ADVICE_ACCOUNT_REBAL_FREQ VARCHAR2(1 BYTE) 
, ADVICE_ACCOUNT_INDICATOR VARCHAR2(10 BYTE) 
, LAST_CRC_RATE_CHG_DT DATE 
, SOURCE_CYCLE_DATE DATE 
, PROCESSING_DATE DATE 
, SOURCE_SYSTEM VARCHAR2(80 BYTE)
, PART_TYPE VARCHAR2(11 BYTE) 
, COUNTRY_NAME VARCHAR2(100 BYTE)
, ADVICE_TARGET_MESSAGE_3 NUMBER(38, 0) 
, ADVICE_TARGET_MESSAGE_2 NUMBER(38, 0) 
, ADVICE_TARGET_MESSAGE_1 NUMBER(38, 0) 
, ADDRESS_VALIDITY VARCHAR2(1 BYTE) ,
CONSTRAINT PK_PARTICIPANT PRIMARY KEY 
(
  RETIREMENT_ACCOUNT_ID 
, CLIENT_ID 
, PARTICIPANT_ID 
, PLAN_NUMBER 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;



CREATE TABLE NEWR_REPOS.PARTICIPANT_DELTA
( 
 CLIENT_ID VARCHAR2(10 BYTE) NOT NULL 
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, DIV_SUB_ID VARCHAR2(25 BYTE) 
, RETIREMENT_ACCOUNT_ID VARCHAR2(27 BYTE) NOT NULL 
, CUST_ODS_AGREEMENT_ID VARCHAR2(36 BYTE) 
, FIRST_NAME VARCHAR2(255 BYTE) 
, MIDDLE_NAME VARCHAR2(255 BYTE)
, LAST_NAME VARCHAR2(255 BYTE) 
, NAME_SUFFIX VARCHAR2(4 BYTE) 
, NAME_FORMATTED VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_1 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_2 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_3 VARCHAR2(255 BYTE) 
, PART_ADDRESS_LINE_4 VARCHAR2(255 BYTE)
, PART_ADDRESS_CITY VARCHAR2(255 BYTE)  
, PART_ADDRESS_STATE VARCHAR2(100 BYTE) 
, PART_ADDRESS_ZIP_CODE VARCHAR2(20 BYTE)
, BIRTH_DATE DATE
, AGE NUMBER(38, 0) 
, ATTAINED_AGE NUMBER(7, 2) 
, GENDER_CODE VARCHAR2(10 BYTE)
, GENDER_DESC VARCHAR2(55 BYTE) 
, EMAIL_ADDRESS VARCHAR2(255 BYTE) 
, MARITAL_STATUS_CODE VARCHAR2(5 BYTE)
, MARITAL_STATUS_CODE_DESC VARCHAR2(40 BYTE) 
, PART_PRODUCT_ID VARCHAR2(6 BYTE) 
, PRODUCT_CODE VARCHAR2(2 BYTE)
, PRODUCT_NAME VARCHAR2(20 BYTE) 
, PLAN_CODE VARCHAR2(6 BYTE) 
, PARTICIPANT_STATUS_CODE VARCHAR2(20 BYTE) 
, PART_STATUS_DESC VARCHAR2(10 BYTE) 
, PART_ACCT_STATUS_DATE DATE  
, CLIENT_STATUS VARCHAR2(10 BYTE)
, ACCOUNT_INCEPTION_DATE DATE 
, PLAN_ENTRY_DATE DATE 
, REINSTATEMENT_NOTIFY_DATE DATE 
, QDIA_DATE DATE 
, ENROLLMENT_DATE DATE 
, EMPLOYMENT_DATE DATE 
, ELIGIBLE_FOR_DISTRIBUTION_DATE DATE 
, ELIGIBILITY_REMINDER_DATE DATE 
, ELIGIBILITY_DATE DATE 
, ELIGIBILITY_COMPLETION_DATE DATE 
, ELIGIBILITY_5500_DATE DATE 
, DOLLAR5000_REACHED_DATE DATE 
, DEMOGRAPHIC_EFFECTIVE_DATE DATE 
, AUTO_ENROLLMENT_DATE DATE 
, ALTERNATE_VESTING_DATE DATE 
, TERMINATION_NOTIFICATION_DATE DATE 
, TERMINATION_DATE DATE 
, SUSPENSION_DATE DATE 
, LEAVE_OF_ABSENSE_END_DATE DATE 
, DEFER_DATE DATE
, DEATH_DATE DATE 
, SPOUSE_CONSENT_EXPIRATION_DATE DATE 
, ROTH_FIRST_CONTRIBUTION_DATE DATE  
, FE_START_DATE DATE 
, FE_END_DATE DATE
, NEXT_REBALANCE_DATE DATE 
, MVA_CHARGED_TO_DATE DATE 
, MIN_DISTRIB_ELIGIBILITY_DATE DATE 
, MIN_DISTRIB_BEGIN_DATE_OPTION VARCHAR2(1 BYTE) 
, LAST_TRANSFER_DATE DATE 
, LAST_PLAN_TO_PLAN_TRANSF_DATE DATE 
, LAST_LOAN_DEFAULT_DATE DATE 
, LAST_HARDSHIP_WITHDRAWAL_DATE DATE 
, LAST_CONTRIBUTION_DATE DATE 
, LAST_CONTRIB_RATE_CHANGE_DATE DATE 
, LAST_ALLOC_PCT_CHANGE_DATE DATE 
, INIT_ROLLOVER_DIST_DATE DATE 
, INIT_PARTIAL_TERM_DIST_DATE DATE 
, FREE_LOOK_END_DATE DATE 
, FIRST_DEFAULT_CONTRIB_DATE DATE 
, FIRST_CONTRIBUTION_DATE DATE 
, EXCESS_TRADER_SUSPEND_END_DATE DATE 
, EXCESS_TRADER_SUSP_START_DATE DATE  
, HIGHEST_OUTSTAND_LOAN_BALANCE NUMBER(11, 2) 
, SPOUSE_BIRTH_DATE DATE 
, SPOUSE_NAME VARCHAR2(255 BYTE) 
, YTD_CONTRIBUTIONS NUMBER(15, 2) 
, AUTO_ENROLLMENT_INDICATOR VARCHAR2(10 BYTE) 
, TOTAL_NUMBER_OF_FUNDS NUMBER(38, 0) 
, TERMINATION_REASON_CODE VARCHAR2(2 BYTE) 
, TERM_STAT_REASON_CODE VARCHAR2(2 BYTE) 
, SUSPENSION_MONTHS_FORF_REALLOC NUMBER(38, 0)
, SUSPENSION_MONTHS_ER_CONTRIB NUMBER(38, 0) 
, SUSPENSION_MONTHS_EE_CONTRIB NUMBER(38, 0) 
, PART_SSN VARCHAR2(17 BYTE) 
, PART_SSN_LAST_4 VARCHAR2(4 BYTE) 
, QDRO_FLAG VARCHAR2(1 BYTE) 
, QDRO_STATUS VARCHAR2(1 BYTE) 
, QDRO_BENEFICARY_SSN NUMBER(11, 2) 
, QDIA_INDICATOR VARCHAR2(1 BYTE)
, DEFAULT_ENROLLED_QDIA VARCHAR2(1 BYTE) 
, ROTH_UNRESTRICTED_CONTRIB NUMBER(11, 2) 
, ROTH_SMA_ACCOUNT_NUMBER VARCHAR2(254 BYTE) 
, ROTH_IPRR_CONTRIBUTIONS NUMBER(11, 2) 
, ROTH_YEAR VARCHAR2(4 BYTE) 
, ROTH_DEFERRAL_CONTRIBUTIONS NUMBER(11, 2) 
, ROLL_CONTRIBUTION_PRIOR_YEAR NUMBER(11, 2) 
, ROLL_CONTRIBUTION_CURRENT_YEAR NUMBER(11, 2) 
, ROLL_ACCOUNT_TYPE VARCHAR2(1 BYTE)
, PRE1987_EE_AFTERTAX_CONTRIB NUMBER(11, 2) 
, PRE_TAX_401K_CONTRIB_PRIOR NUMBER(11, 2) 
, PRE_TAX_401K_CONTRIB_CURRENT NUMBER(11, 2)
, POST1986_EE_AFTERTAX_CONTRIB NUMBER(11, 2) 
, POST88_SURENDER VARCHAR2(15 BYTE) 
, PLAN_YEAR_COMPENSATION_PRIOR NUMBER(15, 2) 
, PLAN_YEAR_COMPENSATION_CURRENT NUMBER(15, 2) 
, NONQUAL_IND VARCHAR2(10 BYTE) 
, EE_CONTRIB_TAXED_BY_STATE NUMBER(38, 0)
, EE_CONTRIB_401K_STATE_TAX_FLAG VARCHAR2(1 BYTE) 
, EE_CONTRIB_401K_PRIOR_YEAR NUMBER(11, 2) 
, EE_CONTRIB_401K_CURRENT_YEAR NUMBER(11, 2) 
, EE_CONTRIB_YTD NUMBER(7, 2) 
, ee_contrib_prior_tax_year NUMBER(7, 2) 
, DIVIDEND_PASS_THRU_INDICATOR NUMBER(4, 1) 
, DIVIDEND_PASS_THRU_ELECTION NUMBER(5, 4) 
, DIVIDEND_PASS_THRU_ELECTION_PCT NUMBER(4, 1)  
, CONTRIBUTION_415_PRIOR NUMBER(11, 2) 
, CONTRIBUTION_415_CURRENT NUMBER(11, 2) 
, EMPLOYEE_ID VARCHAR2(13 BYTE) 
, EMPLOYEE_NUMBER VARCHAR2(40 BYTE) 
, EMPLOYEE_NUMBER_2 VARCHAR2(40 BYTE) 
, EMPLOYMENT_STATUS_REASON VARCHAR2(1 BYTE) 
, KEY_EMPLOYEE_INDICATOR VARCHAR2(1 BYTE)
, RELATED_PARTICIPANT_ID VARCHAR2(25 BYTE) 
, SMA_FUND_BALANCE NUMBER(15, 2) 
, SDBO_HOLD_HARMLESS VARCHAR2(1 BYTE) 
, FINANCIAL_ENGINS_PROSPECT_CODE VARCHAR2(1 BYTE) 
, WITHDRAWAL_RESTRICTION_REASON VARCHAR2(1 BYTE) 
, WITHDRAWAL_RESTRICTION VARCHAR2(1 BYTE) 
, VERY_IMPORTANT_PERSON_INDICAT VARCHAR2(254 BYTE) 
, TRADE_ACTIVITY VARCHAR2(2 BYTE) 
, TAX_TREATY_COUNTRY_CODE VARCHAR2(3 BYTE) 
, SOURCE_ADJ_VEST_PERCENT NUMBER(4, 3) 
, REDUCTION_401K_OPTION VARCHAR2(254 BYTE) 
, PUERTO_RICO_RESIDENT VARCHAR2(3 BYTE) 
, PRIOR_HCE_INDICATOR VARCHAR2(1 BYTE) 
, PLAN_REFERENCE_KEY VARCHAR2(8 BYTE) 
, PERIODS_OF_CONTINUOUS_SERVICE NUMBER(38, 0) 
, PAYROLL_FREQUENCY VARCHAR2(1 BYTE) 
, PAY_GROUP_ID VARCHAR2(5 BYTE) 
, PERSON_FLAG VARCHAR2(1 BYTE) 
, INSTALLMENT_STATUS VARCHAR2(10 BYTE) 
, HCE_STATUS VARCHAR2(10 BYTE) 
, CATCHUP_ELIGIBLE_FLAG VARCHAR2(1 BYTE) 
, ACCOUNT_TYPE_CODE_DESC VARCHAR2(40 BYTE) 
, ACCOUNT_TYPE_CODE VARCHAR2(30 BYTE) 
, ACCOUNT_TYPE VARCHAR2(55 BYTE)
, STATUS_16B VARCHAR2(10 BYTE) 
, YTD_HOURS_WORKED VARCHAR2(10 BYTE) 
, PHONE VARCHAR2(32 BYTE) 
, PART_PERSON_FLAG VARCHAR2(1 BYTE)
, PAYROLL_LOCATION VARCHAR2(5 BYTE)  
, LOCATION_CODE VARCHAR2(4 BYTE)  
, LINE_OF_BUSINESS VARCHAR2(3 BYTE) 
, AGG_SYS_KEY VARCHAR2(24 BYTE)  
, WITHHOLDING_PCT_OVERRIDE NUMBER(5, 4) 
, WITHHOLDING_AMOUNT_OVERRIDE NUMBER(11, 2) 
, WITHHOLDING_OVERRIDE VARCHAR2(1 BYTE)
, ORACLE_PLAN_RULE_ID VARCHAR2(80 BYTE) 
, OLD_ADVICE_ACCOUNT VARCHAR2(80 BYTE) 
, NET_401K_ELECTIVE_DEFERRALS NUMBER(11, 2) 
, MIN_DISTRIB_SUPPRESS_OPTION VARCHAR2(1 BYTE) 
, MIN_DISTRIB_CALCULATION_METHOD VARCHAR2(1 BYTE)
, MATCH_PAYROLL_GENERIC_GROUPING VARCHAR2(5 BYTE) 
, MANAGED_ACCT_SALARY_AT_ENROLL NUMBER(11, 2) 
, LIFETIME_DSC_AMOUNT NUMBER(11, 2)
, LAST_CONTRIBUTION_AMT_GROSS NUMBER(17, 2)
, LANGUAGE_PRINT_PREFERENCE VARCHAR2(3 BYTE) 
, INSIDE_TRADING_16B_RESTRICT_ID VARCHAR2(1 BYTE)  
, ILIP_EQUITY_WASH_RESIDUAL_AMT NUMBER(11, 2) 
, HUMAN_RESOURCE_STATUS_CODE VARCHAR2(10 BYTE) 
, HOURS_OF_SERVICE NUMBER(38, 0) 
, HIGHLY_COMPENSATED_EE_FLAG VARCHAR2(1 BYTE) 
, HIGH_LOAN_BALANCE_AMOUNT NUMBER(11, 2) 
, HCE_INDICATOR VARCHAR2(1 BYTE) 
, GROUP_PAYMENT_STATUS_FLAG VARCHAR2(1 BYTE) 
, GROUP_IV_ID VARCHAR2(2 BYTE) 
, FOREIGN_COUNTRY_CODE VARCHAR2(3 BYTE)
, FLAG_16B VARCHAR2(1 BYTE) 
, FEDERAL_W4P_FORM_STATUS VARCHAR2(1 BYTE)
, EXCESS_TRADER_SUSPEND_FLAG VARCHAR2(1 BYTE) 
, ESOP_DIVERSIFICATION_SHARES NUMBER(11, 2) 
, ER_AFTER_TAX_AMOUNT NUMBER(11, 2) 
, EQUITY_WASH_AMOUNT NUMBER(11, 2) 
, ELIGIBLE_FOR_BONUS VARCHAR2(1 BYTE) 
, ELIGIBILITY_EXCLUSION VARCHAR2(1 BYTE) 
, ELIG_ROLLOVER_DISTRIBUTIONS NUMBER(11, 2) 
, EGTRRA_TARGET_MESSAGE_ID NUMBER(38, 0) 
, DEFERRAL_GROUPING_ID VARCHAR2(4 BYTE) 
, DEFAULT_INVESTMENT_FLAG VARCHAR2(20 BYTE)  
, DEFAULT_DEFERRAL_FLAG VARCHAR2(20 BYTE)
, DEATH_BENEFIT_PERCENTAGE NUMBER(38, 0)
, STATE_CONTRIB_TAXED_BY_FLAG VARCHAR2(1 BYTE) 
, CLIENT_PASS_THRU_IDENTIFIER VARCHAR2(10 BYTE) 
, BROKERAGE_ACCOUNT_NUMBER VARCHAR2(20 BYTE)
, BENEFICIARY_CODE VARCHAR2(1 BYTE) 
, AUTOMATIC_INCREASE_FLAG VARCHAR2(1 BYTE) 
, ANNUAL_SALARY NUMBER(11, 2) 
, ANNUAL_DIST_AMOUNT NUMBER(11, 2) 
, ALTERNATE_TAXABILITY_STATE VARCHAR2(2 BYTE) 
, ALTERNATE_ACCOUNT_NUMBER VARCHAR2(100 BYTE) 
, ADVICE_ACCOUNT_REBAL_FREQ VARCHAR2(1 BYTE) 
, ADVICE_ACCOUNT_INDICATOR VARCHAR2(10 BYTE) 
, LAST_CRC_RATE_CHG_DT DATE
, SOURCE_CYCLE_DATE DATE 
, PROCESSING_DATE DATE 
, SOURCE_SYSTEM VARCHAR2(80 BYTE)
, PART_TYPE VARCHAR2(11 BYTE) 
, COUNTRY_NAME VARCHAR2(100 BYTE)
, ADVICE_TARGET_MESSAGE_3 NUMBER(38, 0) 
, ADVICE_TARGET_MESSAGE_2 NUMBER(38, 0) 
, ADVICE_TARGET_MESSAGE_1 NUMBER(38, 0) 
, ADDRESS_VALIDITY VARCHAR2(1 BYTE) 
, DELTA_OP_IND VARCHAR(1)
)
TABLESPACE NEWR_REPOS_DATA
;


CREATE TABLE NEWR_REPOS.TXN_DELTA
( 
  CLIENT_ID VARCHAR2(10 BYTE)  
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, TRADE_DATE DATE NOT NULL 
, RUN_DATE DATE NOT NULL 
, RUN_TIME VARCHAR2(20 BYTE) NOT NULL
, BASE_TRANSACTION_CODE VARCHAR2(20 BYTE) NOT NULL 
, ACTIVITY_TYPE NUMBER(32, 0) NOT NULL 
, REV_CODE VARCHAR2(20 BYTE) NOT NULL  
, FUND_IV VARCHAR2(20 BYTE) 
, FUND_NUMBER VARCHAR2(15 BYTE) 
, FUND_SRC VARCHAR2(20 BYTE) 
, MONEY_SOURCE VARCHAR2(10 BYTE) 
, CASH NUMBER(13, 2) 
, UNINVESTED_CASH NUMBER(13, 2) 
, SHARES NUMBER(13, 4) 
, SHARE_PRICE NUMBER(13, 6) 
, SEQUENCE_NUMBER VARCHAR2(50 BYTE) NOT NULL 
, POSTING_PROCESS_COUNTER VARCHAR2(20 BYTE) NOT NULL 
, USAGE_CODE_1 VARCHAR2(20 BYTE) 
, USAGE_CODE_2 VARCHAR2(20 BYTE) 
, USAGE_CODE_3 VARCHAR2(20 BYTE) 
, USAGE_CODE_4 VARCHAR2(20 BYTE) 
, USAGE_CODE_5 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_1 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_2 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_3 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_4 VARCHAR2(20 BYTE) 
, STANDARD_USAGE_CODE_5 VARCHAR2(20 BYTE) 
, PREVIOUS_ACTIVITY_DATE DATE 
, CATEGORY VARCHAR2(100 BYTE) 
, OTHER_CASH NUMBER(13, 2)
, ACTIVITY VARCHAR2(30 BYTE) 
, NET_CURRENCY_VALUE NUMBER(13, 2) 
, ALT_POSTING_PROCESS_COUNTER NUMBER(38, 0) 
, ASSOCIATED_ACTIVITY NUMBER(38, 0)  
, PAY_PERIOD_END_DATE DATE 
, REC_CODE VARCHAR2(20 BYTE) 
, RECORD_TYPE VARCHAR2(20 BYTE) 
, RESERVED_CASH_SHARES_IND NUMBER(15, 2)
, REVERSAL_REASON VARCHAR2(20 BYTE) 
, REVERSE_RUN_DATE DATE 
, SHARE_CLASS VARCHAR2(20 BYTE)
, SHARE_COST NUMBER(13, 2)
, TRAN_SEQ NUMBER(32, 0) 
, VOUCHER_NUMBER NUMBER(38, 0) 
, REC_TYPE VARCHAR2(6 BYTE) 
, ETIN_NUM VARCHAR2(9 BYTE) 
, FILEID_EXT VARCHAR2(20 BYTE) 
, FILEID_NAME VARCHAR2(20 BYTE) 
, FILEID_PTR_INDIC VARCHAR2(20 BYTE) 
, MARGIN_CODE VARCHAR2(10 BYTE)
, PART_EXT VARCHAR2(20 BYTE) 
, PART_EXT1 VARCHAR2(20 BYTE) 
, PART_NUM_X VARCHAR2(9 BYTE) 
, PART_NUM NUMBER(32, 0) 
, PART_SUB_PLAN VARCHAR2(6 BYTE) 
, PEND_STAT VARCHAR2(20 BYTE)
, PLAN_NUM VARCHAR2(6 BYTE)
, SEPARATE_ACCT VARCHAR2(20 BYTE) 
, COMPANY_CODE VARCHAR2(20 BYTE)  
, CURRENCY_CODE VARCHAR2(5 BYTE)
, CURRENCY_VALUE NUMBER(13, 2)
, SUB_ACTIVITY_CODE NUMBER(38, 0) 
, SOURCE_CYCLE_DATE DATE 
, TRADE_TYPE VARCHAR2(10 BYTE)
, SOURCE_PROCESSING_DATE DATE 
, TRAN_CODE VARCHAR2(20 BYTE) 
, SOURCE_SYSTEM VARCHAR2(40 BYTE) 
, USE_PLAN_YEAR_FLAG VARCHAR2(10 BYTE) 
, XR_RATE NUMBER(11, 6)  
, XR_TYPE VARCHAR2(20 BYTE) 
, PLAN_SEQUENCE VARCHAR2(6 BYTE)
, ACTIVITY_CODE_DESCRIPTION VARCHAR2(255)
, SEQ_OPER_CODE VARCHAR2(20 BYTE) 
, TRANSFORM_HASH_KEY NUMBER(38, 0)
, DELTA_OP_IND VARCHAR(1)
)
TABLESPACE NEWR_REPOS_DATA
;

GRANT SELECT ON NEWR_REPOS.txn TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.txn TO role_newr_repos_write;


GRANT SELECT ON NEWR_REPOS.participant TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant TO role_newr_repos_write;

GRANT SELECT ON NEWR_REPOS.participant_delta TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant_delta TO role_newr_repos_write;




GRANT SELECT ON NEWR_REPOS.txn_delta TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.txn_delta TO role_newr_repos_write;



--plan

CREATE TABLE NEWR_REPOS.PLAN 
(
  client_id VARCHAR2(10) ,
plan_number VARCHAR2(25) ,
plan_name_line_1 VARCHAR2(255) ,
plan_name_line_2 VARCHAR2(255) ,
plan_address_line_1 VARCHAR2(255) ,
plan_address_line_2 VARCHAR2(255) ,
plan_address_line_3 VARCHAR2(255) ,
plan_address_city VARCHAR2(255) ,
plan_address_state VARCHAR2(255) ,
plan_address_zip_code VARCHAR2(10) ,
sponsor_name_line_1 VARCHAR2(255) ,
sponsor_name_line_2 VARCHAR2(255) ,
sponsor_address1 VARCHAR2(255) ,
sponsor_address2 VARCHAR2(255) ,
sponsor_address3 VARCHAR2(255) ,
sponsor_city VARCHAR2(100) ,
sponsor_state VARCHAR2(3) ,
sponsor_zip_code VARCHAR2(10) ,
sponsor_country VARCHAR2(100) ,
primary_contact_first_name VARCHAR2(255) ,
primary_contact_last_name VARCHAR2(255) ,
primary_contact_phone_no VARCHAR2(80) ,
primary_contact_email VARCHAR2(80) ,
primary_contact_source_system VARCHAR2(10) ,
crm_name VARCHAR2(64) ,
crm_phone VARCHAR2(32) ,
crm_email VARCHAR2(128) ,
plan_manager_name VARCHAR2(80) ,
plan_product_code VARCHAR2(80) ,
plan_product_short_name VARCHAR2(255) ,
grp_product_desc VARCHAR2(40) ,
product_type VARCHAR2(5) ,
irc_code VARCHAR2(100) ,
irc_code_desc VARCHAR2(55) ,
ein_full VARCHAR2(254) ,
ein_number NUMBER(38,0) ,
ein_suffix VARCHAR2(5) ,
plan_issue_date DATE ,
tpa_code VARCHAR2(80) ,
tpa_name VARCHAR2(255) ,
trustee_email VARCHAR2(128) ,
trustee_name VARCHAR2(64) ,
trustee_phone VARCHAR2(32) ,
loans_allowed_flag VARCHAR2(1) ,
loan_401k_elective_limit NUMBER(38,0) ,
loan_max_pct_vested_curr_val NUMBER(3,2) ,
loan_maximum_amount NUMBER(11,2) ,
loan_minimum_amount NUMBER(11,2) ,
managed_account_flag VARCHAR2(10) ,
managed_account_start_date DATE ,
managed_account_end_date DATE ,
managed_accounts_program VARCHAR2(80) ,
ma_cust_adv_pgv VARCHAR2(5) ,
ma_ama_ria_firm_name VARCHAR2(255) ,
ma_init_freelook_start_date DATE ,
ma_init_freelook_start_durn VARCHAR2(80) ,
ma_init_freelook_start_window VARCHAR2(80) ,
ma_promo_freelook_start_date DATE ,
ma_promo_freelook_start_durn VARCHAR2(80) ,
ma_promo_freelook_start_window VARCHAR2(80) ,
managed_account_service_ind VARCHAR2(1) ,
managed_account_fee_type VARCHAR2(80) ,
managed_account_fee VARCHAR2(80) ,
ma_voya_as_advisor_is_qdia VARCHAR2(80) ,
ma1_override_amount NUMBER(10,6) ,
ma2_override_amount NUMBER(5,2) ,
mai_override_amount NUMBER(6,2) ,
mam_override_amount NUMBER(5,2) ,
managed_account_default_salary VARCHAR2(80) ,
ma_program_adoption_type VARCHAR2(80) ,
ma_program_default VARCHAR2(80) ,
ma_program_pricing_model VARCHAR2(80) ,
qdia_indicator VARCHAR2(1) ,
qdia_option VARCHAR2(1) ,
qdia_effective_date DATE ,
qdia_default_fund_iv VARCHAR2(5) ,
qdia_default_fund_number VARCHAR2(20) ,
qdia_portfolio_type_fund_name VARCHAR2(255) ,
qdia_portfolio_fund_series VARCHAR2(80) ,
model_portf_qdia_tgt_date_ind VARCHAR2(1) ,
model_portfolio_qdia_model_num VARCHAR2(5) ,
asset_alloc_made_easy_is_qdia VARCHAR2(8) ,
fiduciary_service_flag VARCHAR2(10) ,
fiduciary_services_program VARCHAR2(80) ,
fid_ser_program_name VARCHAR2(255) ,
fid_ser_start_date DATE ,
fid_ser_end_date DATE ,
fid_ser_fund_menu VARCHAR2(6) ,
fid_ser_fee_ded_meth VARCHAR2(50) ,
erisa_flag VARCHAR2(80) ,
sdbo_status VARCHAR2(80) ,
ach_online_payment_flag VARCHAR2(10) ,
enh_send_notice_flag VARCHAR2(1) ,
voya_send_notices_flag VARCHAR2(1) ,
plan_expand_flag VARCHAR2(1) ,
model_portfolio_fix_acct_flag VARCHAR2(1) ,
uses_contrib_rate_escalator VARCHAR2(10) ,
uses_eligibility_module VARCHAR2(10) ,
uses_loan_sweep_module VARCHAR2(10) ,
is_free_look_recurring VARCHAR2(80) ,
dwe_status VARCHAR2(32) ,
fee_deduction_method VARCHAR2(30) ,
income_secure_ma_flag VARCHAR2(80) ,
Plan_Unallocated_flag VARCHAR2(1) ,
usb_pgm_flag VARCHAR2(1) ,
auto_enroll VARCHAR2(1) ,
auto_enroll_eaca_qaca_ind VARCHAR2(10) ,
roth_ind VARCHAR2(1) ,
market_indicator VARCHAR2(2) ,
exchange_indicator VARCHAR2(1) ,
alternate_acct_number_ind VARCHAR2(1) ,
financial_engine_fees_ind VARCHAR2(10) ,
grp_plan_indicator VARCHAR2(1) ,
initial_notification_srvc_ind VARCHAR2(1) ,
migration_indicator VARCHAR2(1) ,
permissible_withdrawal_ind VARCHAR2(1) ,
advice_part_elig_allowed VARCHAR2(1) ,
plan_administrator_name VARCHAR2(255) ,
plan_company_code VARCHAR2(3) ,
plan_end_mmdd VARCHAR2(4) ,
model_portfolio_fix_acct_name VARCHAR2(255) ,
money_out_service_model VARCHAR2(1) ,
max_deferral_amount NUMBER(11,2) ,
max_deferral_percent NUMBER(5,4) ,
mtf_fee_recovery VARCHAR2(80) ,
mtf_override_amout NUMBER(10,2) ,
safe_harbor_amount VARCHAR2(80) ,
safe_harbor_percent VARCHAR2(80) ,
number_loans_allowed VARCHAR2(10) ,
dac_override_amount NUMBER(15,2) ,
crc_type VARCHAR2(1) ,
employer_stock VARCHAR2(5) ,
end_date DATE ,
financial_advisor VARCHAR2(80) ,
fund_menu VARCHAR2(80) ,
grp_product_name VARCHAR2(255) ,
hardship_suspension VARCHAR2(10) ,
old_billing_group VARCHAR2(80) ,
old_fixed_fund_number VARCHAR2(80) ,
old_product_code VARCHAR2(80) ,
plan_reference_key VARCHAR2(80) ,
plan_system_key VARCHAR2(80) ,
rep_id VARCHAR2(80) ,
start_date VARCHAR2(80) ,
superior_plan_name VARCHAR2(255) ,
superior_plan_reference_key VARCHAR2(80) ,
vesting_data_source VARCHAR2(10) ,
wealth_management_end_date DATE ,
wealth_management_start_date DATE ,
wealth_mgmt_retirement_allowed VARCHAR2(80) ,
billing_group VARCHAR2(6) ,
ease_db_plan_id VARCHAR2(10) ,
open_arch_menu_type VARCHAR2(80) ,
pcf_fee_recovery VARCHAR2(80) ,
pcf_override_amount NUMBER(8,2) ,
portfolio_blueprint_tier_amt VARCHAR2(80) ,
ppf_fee_recovery VARCHAR2(80) ,
ppf_override_amount NUMBER(8,2) ,
proposal_mail_date DATE ,
ss_plan_sept_act_code VARCHAR2(3) ,
market_code VARCHAR2(80) ,
source_cycle_date DATE ,
source_processing_date DATE ,
source_system VARCHAR2(80) ,
underlying_source_system VARCHAR2(80) ,
admin_system VARCHAR2(10) ,
CONSTRAINT PK_PLAN PRIMARY KEY 
(
  PLAN_NUMBER 
, CLIENT_ID 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;

-- TABLE: NEWR_REPOS.plan
--

GRANT SELECT ON NEWR_REPOS.plan TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.plan TO role_newr_repos_write;

--plan

   CREATE TABLE NEWR_REPOS.PLAN_DELTA 
(
  client_id VARCHAR2(10) ,
plan_number VARCHAR2(25) ,
plan_name_line_1 VARCHAR2(255) ,
plan_name_line_2 VARCHAR2(255) ,
plan_address_line_1 VARCHAR2(255) ,
plan_address_line_2 VARCHAR2(255) ,
plan_address_line_3 VARCHAR2(255) ,
plan_address_city VARCHAR2(255) ,
plan_address_state VARCHAR2(255) ,
plan_address_zip_code VARCHAR2(10) ,
sponsor_name_line_1 VARCHAR2(255) ,
sponsor_name_line_2 VARCHAR2(255) ,
sponsor_address1 VARCHAR2(255) ,
sponsor_address2 VARCHAR2(255) ,
sponsor_address3 VARCHAR2(255) ,
sponsor_city VARCHAR2(100) ,
sponsor_state VARCHAR2(3) ,
sponsor_zip_code VARCHAR2(10) ,
sponsor_country VARCHAR2(100) ,
primary_contact_first_name VARCHAR2(255) ,
primary_contact_last_name VARCHAR2(255) ,
primary_contact_phone_no VARCHAR2(80) ,
primary_contact_email VARCHAR2(80) ,
primary_contact_source_system VARCHAR2(10) ,
crm_name VARCHAR2(64) ,
crm_phone VARCHAR2(32) ,
crm_email VARCHAR2(128) ,
plan_manager_name VARCHAR2(80) ,
plan_product_code VARCHAR2(80) ,
plan_product_short_name VARCHAR2(255) ,
grp_product_desc VARCHAR2(40) ,
product_type VARCHAR2(5) ,
irc_code VARCHAR2(100) ,
irc_code_desc VARCHAR2(55) ,
ein_full VARCHAR2(254) ,
ein_number NUMBER(38,0) ,
ein_suffix VARCHAR2(5) ,
plan_issue_date DATE ,
tpa_code VARCHAR2(80) ,
tpa_name VARCHAR2(255) ,
trustee_email VARCHAR2(128) ,
trustee_name VARCHAR2(64) ,
trustee_phone VARCHAR2(32) ,
loans_allowed_flag VARCHAR2(1) ,
loan_401k_elective_limit NUMBER(38,0) ,
loan_max_pct_vested_curr_val NUMBER(3,2) ,
loan_maximum_amount NUMBER(11,2) ,
loan_minimum_amount NUMBER(11,2) ,
managed_account_flag VARCHAR2(10) ,
managed_account_start_date DATE ,
managed_account_end_date DATE ,
managed_accounts_program VARCHAR2(80) ,
ma_cust_adv_pgv VARCHAR2(5) ,
ma_ama_ria_firm_name VARCHAR2(255) ,
ma_init_freelook_start_date DATE ,
ma_init_freelook_start_durn VARCHAR2(80) ,
ma_init_freelook_start_window VARCHAR2(80) ,
ma_promo_freelook_start_date DATE ,
ma_promo_freelook_start_durn VARCHAR2(80) ,
ma_promo_freelook_start_window VARCHAR2(80) ,
managed_account_service_ind VARCHAR2(1) ,
managed_account_fee_type VARCHAR2(80) ,
managed_account_fee VARCHAR2(80) ,
ma_voya_as_advisor_is_qdia VARCHAR2(80) ,
ma1_override_amount NUMBER(10,6) ,
ma2_override_amount NUMBER(5,2) ,
mai_override_amount NUMBER(6,2) ,
mam_override_amount NUMBER(5,2) ,
managed_account_default_salary VARCHAR2(80) ,
ma_program_adoption_type VARCHAR2(80) ,
ma_program_default VARCHAR2(80) ,
ma_program_pricing_model VARCHAR2(80) ,
qdia_indicator VARCHAR2(1) ,
qdia_option VARCHAR2(1) ,
qdia_effective_date DATE ,
qdia_default_fund_iv VARCHAR2(5) ,
qdia_default_fund_number VARCHAR2(20) ,
qdia_portfolio_type_fund_name VARCHAR2(255) ,
qdia_portfolio_fund_series VARCHAR2(80) ,
model_portf_qdia_tgt_date_ind VARCHAR2(1) ,
model_portfolio_qdia_model_num VARCHAR2(5) ,
asset_alloc_made_easy_is_qdia VARCHAR2(8) ,
fiduciary_service_flag VARCHAR2(10) ,
fiduciary_services_program VARCHAR2(80) ,
fid_ser_program_name VARCHAR2(255) ,
fid_ser_start_date DATE ,
fid_ser_end_date DATE ,
fid_ser_fund_menu VARCHAR2(6) ,
fid_ser_fee_ded_meth VARCHAR2(50) ,
erisa_flag VARCHAR2(80) ,
sdbo_status VARCHAR2(80) ,
ach_online_payment_flag VARCHAR2(10) ,
enh_send_notice_flag VARCHAR2(1) ,
voya_send_notices_flag VARCHAR2(1) ,
plan_expand_flag VARCHAR2(1) ,
model_portfolio_fix_acct_flag VARCHAR2(1) ,
uses_contrib_rate_escalator VARCHAR2(10) ,
uses_eligibility_module VARCHAR2(10) ,
uses_loan_sweep_module VARCHAR2(10) ,
is_free_look_recurring VARCHAR2(80) ,
dwe_status VARCHAR2(32) ,
fee_deduction_method VARCHAR2(30) ,
income_secure_ma_flag VARCHAR2(80) ,
Plan_Unallocated_flag VARCHAR2(1) ,
usb_pgm_flag VARCHAR2(1) ,
auto_enroll VARCHAR2(1) ,
auto_enroll_eaca_qaca_ind VARCHAR2(10) ,
roth_ind VARCHAR2(1) ,
market_indicator VARCHAR2(2) ,
exchange_indicator VARCHAR2(1) ,
alternate_acct_number_ind VARCHAR2(1) ,
financial_engine_fees_ind VARCHAR2(10) ,
grp_plan_indicator VARCHAR2(1) ,
initial_notification_srvc_ind VARCHAR2(1) ,
migration_indicator VARCHAR2(1) ,
permissible_withdrawal_ind VARCHAR2(1) ,
advice_part_elig_allowed VARCHAR2(1) ,
plan_administrator_name VARCHAR2(255) ,
plan_company_code VARCHAR2(3) ,
plan_end_mmdd VARCHAR2(4) ,
model_portfolio_fix_acct_name VARCHAR2(255) ,
money_out_service_model VARCHAR2(1) ,
max_deferral_amount NUMBER(11,2) ,
max_deferral_percent NUMBER(5,4) ,
mtf_fee_recovery VARCHAR2(80) ,
mtf_override_amout NUMBER(10,2) ,
safe_harbor_amount VARCHAR2(80) ,
safe_harbor_percent VARCHAR2(80) ,
number_loans_allowed VARCHAR2(10) ,
dac_override_amount NUMBER(15,2) ,
crc_type VARCHAR2(1) ,
employer_stock VARCHAR2(5) ,
end_date DATE ,
financial_advisor VARCHAR2(80) ,
fund_menu VARCHAR2(80) ,
grp_product_name VARCHAR2(255) ,
hardship_suspension VARCHAR2(10) ,
old_billing_group VARCHAR2(80) ,
old_fixed_fund_number VARCHAR2(80) ,
old_product_code VARCHAR2(80) ,
plan_reference_key VARCHAR2(80) ,
plan_system_key VARCHAR2(80) ,
rep_id VARCHAR2(80) ,
start_date VARCHAR2(80) ,
superior_plan_name VARCHAR2(255) ,
superior_plan_reference_key VARCHAR2(80) ,
vesting_data_source VARCHAR2(10) ,
wealth_management_end_date DATE ,
wealth_management_start_date DATE ,
wealth_mgmt_retirement_allowed VARCHAR2(80) ,
billing_group VARCHAR2(6) ,
ease_db_plan_id VARCHAR2(10) ,
open_arch_menu_type VARCHAR2(80) ,
pcf_fee_recovery VARCHAR2(80) ,
pcf_override_amount NUMBER(8,2) ,
portfolio_blueprint_tier_amt VARCHAR2(80) ,
ppf_fee_recovery VARCHAR2(80) ,
ppf_override_amount NUMBER(8,2) ,
proposal_mail_date DATE ,
ss_plan_sept_act_code VARCHAR2(3) ,
market_code VARCHAR2(80) ,
source_cycle_date DATE ,
source_processing_date DATE ,
source_system VARCHAR2(80) ,
underlying_source_system VARCHAR2(80) ,
admin_system VARCHAR2(10) ,
record_Keeping_group_ind  VARCHAR2(20 BYTE) ,
DELTA_OP_IND varchar2(1)
)
TABLESPACE NEWR_REPOS_DATA
;

-- TABLE: NEWR_REPOS.plan
--

GRANT SELECT ON NEWR_REPOS.plan_DELTA TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.plan_DELTA TO role_newr_repos_write;




CREATE TABLE NEWR_REPOS.PARTICIPANT_CORE_BALANCE 
(
retirement_account_id VARCHAR2(36)  ,
client_id VARCHAR2(10)  ,
plan_number VARCHAR2(25)  ,
participant_id VARCHAR2(25)  ,
fund_number VARCHAR2(15)  ,
money_source VARCHAR2(10)  ,
money_source_name VARCHAR2(64) ,
fund_iv VARCHAR2(10)  NOT NULL,
fund_name VARCHAR2(100) ,
money_type_description VARCHAR2(2) ,
cash_value_amount NUMBER(17,2) ,
total_shares NUMBER(17,4) ,
share_price NUMBER(19,6) ,
sdba_cash_value_amount NUMBER(15,2) ,
sdba_trade_date DATE ,
ytd_contributions NUMBER(17,2) ,
vested_balance NUMBER(15,2) ,
vested_percent NUMBER(15,2) ,
uninvested_balance NUMBER(15,2) ,
contribution_gross NUMBER(15,2) ,
contribution_current_fis_year VARCHAR2(25) ,
current_net_contribution NUMBER(15,2) ,
contrib_payment_attributable NUMBER(15,2) ,
contribution_alloc_pct NUMBER(13,4) ,
net_dollars NUMBER(15,2) ,
disbursements_fee NUMBER(15,2) ,
disbursements_withdrawal NUMBER(15,2) ,
disbursements_termination NUMBER(15,2) ,
disbursements_installment NUMBER(15,2) ,
loan_issues NUMBER(15,2) ,
loan_repayment_interest NUMBER(15,2) ,
loan_repayment_principal NUMBER(15,2) ,
debits_miscellanous NUMBER(15,2) ,
receipts_miscellanous NUMBER(15,2) ,
transfers_in NUMBER(15,2) ,
transfers_out NUMBER(15,2) ,
debits_other NUMBER(15,2) ,
cash_earnings NUMBER(15,2) ,
dividend_earnings NUMBER(15,2) ,
shares_gain_loss_earnings NUMBER(13,4) ,
accrued_dividend_amount NUMBER(15,4) ,
annual_dividend_amount NUMBER(15,4) ,
credited_forfeitures NUMBER(15,2) ,
debited_forfeitures NUMBER(15,2) ,
conversions_in NUMBER(15,2) ,
conversions_out NUMBER(15,2) ,
shares_purchased NUMBER(13,4) ,
shares_receipted NUMBER(13,4) ,
shares_sold NUMBER(13,4) ,
shares_distributed NUMBER(15,2) ,
shares_forfeited NUMBER(15,2) ,
cash_credit_pending NUMBER(15,2) ,
shares_credit_pending NUMBER(15,2) ,
cash_debit_pending NUMBER(15,2) ,
shares_debit_pending NUMBER(15,2) ,
fund_margin_code VARCHAR2(10) ,
account_fund_separate VARCHAR2(10) ,
insurance_premium_paid NUMBER(15,2) ,
trade_date DATE ,
source_cycle_date DATE ,
valuation_date DATE ,
action_code VARCHAR2(1) ,
source_system VARCHAR2(80) ,
CONSTRAINT PK_PRIMARY_CORE_BALANCE PRIMARY KEY 
(
retirement_account_id
, MONEY_SOURCE  
, FUND_IV 
, PLAN_NUMBER 
, PARTICIPANT_ID 
, FUND_NUMBER 
, CLIENT_ID 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;
--participant_core_balance_monthly

CREATE TABLE NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY 
(
retirement_account_id VARCHAR2(36)  ,
client_id VARCHAR2(10)  ,
plan_number VARCHAR2(25)  ,
participant_id VARCHAR2(25)  ,
fund_number VARCHAR2(15)  ,
money_source VARCHAR2(10)  ,
money_source_name VARCHAR2(64) ,
fund_iv VARCHAR2(10)  NOT NULL,
fund_name VARCHAR2(100) ,
money_type_description VARCHAR2(2) ,
cash_value_amount NUMBER(17,2) ,
total_shares NUMBER(17,4) ,
share_price NUMBER(19,6) ,
sdba_cash_value_amount NUMBER(15,2) ,
sdba_trade_date DATE ,
ytd_contributions NUMBER(17,2) ,
vested_balance NUMBER(15,2) ,
vested_percent NUMBER(15,2) ,
uninvested_balance NUMBER(15,2) ,
contribution_gross NUMBER(15,2) ,
contribution_current_fis_year VARCHAR2(25) ,
current_net_contribution NUMBER(15,2) ,
contrib_payment_attributable NUMBER(15,2) ,
contribution_alloc_pct NUMBER(13,4) ,
net_dollars NUMBER(15,2) ,
disbursements_fee NUMBER(15,2) ,
disbursements_withdrawal NUMBER(15,2) ,
disbursements_termination NUMBER(15,2) ,
disbursements_installment NUMBER(15,2) ,
loan_issues NUMBER(15,2) ,
loan_repayment_interest NUMBER(15,2) ,
loan_repayment_principal NUMBER(15,2) ,
debits_miscellanous NUMBER(15,2) ,
receipts_miscellanous NUMBER(15,2) ,
transfers_in NUMBER(15,2) ,
transfers_out NUMBER(15,2) ,
debits_other NUMBER(15,2) ,
cash_earnings NUMBER(15,2) ,
dividend_earnings NUMBER(15,2) ,
shares_gain_loss_earnings NUMBER(13,4) ,
accrued_dividend_amount NUMBER(15,4) ,
annual_dividend_amount NUMBER(15,4) ,
credited_forfeitures NUMBER(15,2) ,
debited_forfeitures NUMBER(15,2) ,
conversions_in NUMBER(15,2) ,
conversions_out NUMBER(15,2) ,
shares_purchased NUMBER(13,4) ,
shares_receipted NUMBER(13,4) ,
shares_sold NUMBER(13,4) ,
shares_distributed NUMBER(15,2) ,
shares_forfeited NUMBER(15,2) ,
cash_credit_pending NUMBER(15,2) ,
shares_credit_pending NUMBER(15,2) ,
cash_debit_pending NUMBER(15,2) ,
shares_debit_pending NUMBER(15,2) ,
fund_margin_code VARCHAR2(10) ,
account_fund_separate VARCHAR2(10) ,
insurance_premium_paid NUMBER(15,2) ,
trade_date DATE ,
source_cycle_date DATE ,
valuation_date DATE ,
action_code VARCHAR2(1) ,
source_system VARCHAR2(80), 
CONSTRAINT PK_PRIMARY_CORE_BALANCE_MONTHLY PRIMARY KEY 
(
  retirement_account_id
, MONEY_SOURCE  
, FUND_IV 
, PLAN_NUMBER 
, PARTICIPANT_ID 
, FUND_NUMBER 
, CLIENT_ID
, source_cycle_date
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;

-- TABLE: NEWR_REPOS.participant_core_balance
--

GRANT SELECT ON NEWR_REPOS.participant_core_balance TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant_core_balance TO role_newr_repos_write;

-- TABLE: NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY
-- 

GRANT SELECT ON NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY TO role_newr_repos_write;

CREATE TABLE NEWR_REPOS.PARTICIPANT_CORE_BALANCE_DELTA 
(
retirement_account_id VARCHAR2(36)  ,
client_id VARCHAR2(10)  ,
plan_number VARCHAR2(25)  ,
participant_id VARCHAR2(25)  ,
fund_number VARCHAR2(15)  ,
money_source VARCHAR2(10)  ,
money_source_name VARCHAR2(64) ,
fund_iv VARCHAR2(10)  NOT NULL,
fund_name VARCHAR2(100) ,
money_type_description VARCHAR2(2) ,
cash_value_amount NUMBER(17,2) ,
total_shares NUMBER(17,4) ,
share_price NUMBER(19,6) ,
sdba_cash_value_amount NUMBER(15,2) ,
sdba_trade_date DATE ,
ytd_contributions NUMBER(17,2) ,
vested_balance NUMBER(15,2) ,
vested_percent NUMBER(15,2) ,
uninvested_balance NUMBER(15,2) ,
contribution_gross NUMBER(15,2) ,
contribution_current_fis_year VARCHAR2(25) ,
current_net_contribution NUMBER(15,2) ,
contrib_payment_attributable NUMBER(15,2) ,
contribution_alloc_pct NUMBER(13,4) ,
net_dollars NUMBER(15,2) ,
disbursements_fee NUMBER(15,2) ,
disbursements_withdrawal NUMBER(15,2) ,
disbursements_termination NUMBER(15,2) ,
disbursements_installment NUMBER(15,2) ,
loan_issues NUMBER(15,2) ,
loan_repayment_interest NUMBER(15,2) ,
loan_repayment_principal NUMBER(15,2) ,
debits_miscellanous NUMBER(15,2) ,
receipts_miscellanous NUMBER(15,2) ,
transfers_in NUMBER(15,2) ,
transfers_out NUMBER(15,2) ,
debits_other NUMBER(15,2) ,
cash_earnings NUMBER(15,2) ,
dividend_earnings NUMBER(15,2) ,
shares_gain_loss_earnings NUMBER(13,4) ,
accrued_dividend_amount NUMBER(15,4) ,
annual_dividend_amount NUMBER(15,4) ,
credited_forfeitures NUMBER(15,2) ,
debited_forfeitures NUMBER(15,2) ,
conversions_in NUMBER(15,2) ,
conversions_out NUMBER(15,2) ,
shares_purchased NUMBER(13,4) ,
shares_receipted NUMBER(13,4) ,
shares_sold NUMBER(13,4) ,
shares_distributed NUMBER(15,2) ,
shares_forfeited NUMBER(15,2) ,
cash_credit_pending NUMBER(15,2) ,
shares_credit_pending NUMBER(15,2) ,
cash_debit_pending NUMBER(15,2) ,
shares_debit_pending NUMBER(15,2) ,
fund_margin_code VARCHAR2(10) ,
account_fund_separate VARCHAR2(10) ,
insurance_premium_paid NUMBER(15,2) ,
trade_date DATE ,
source_cycle_date DATE ,
valuation_date DATE ,
action_code VARCHAR2(1) ,
source_system VARCHAR2(80) ,
DELTA_OP_IND varchar2(1)
)
TABLESPACE NEWR_REPOS_DATA
;
--participant_core_balance_monthly

CREATE TABLE NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY_DELTA 
(
retirement_account_id VARCHAR2(36)  ,
client_id VARCHAR2(10)  ,
plan_number VARCHAR2(25)  ,
participant_id VARCHAR2(25)  ,
fund_number VARCHAR2(15)  ,
money_source VARCHAR2(10)  ,
money_source_name VARCHAR2(64) ,
fund_iv VARCHAR2(10)  NOT NULL,
fund_name VARCHAR2(100) ,
money_type_description VARCHAR2(2) ,
cash_value_amount NUMBER(17,2) ,
total_shares NUMBER(17,4) ,
share_price NUMBER(19,6) ,
sdba_cash_value_amount NUMBER(15,2) ,
sdba_trade_date DATE ,
ytd_contributions NUMBER(17,2) ,
vested_balance NUMBER(15,2) ,
vested_percent NUMBER(15,2) ,
uninvested_balance NUMBER(15,2) ,
contribution_gross NUMBER(15,2) ,
contribution_current_fis_year VARCHAR2(25) ,
current_net_contribution NUMBER(15,2) ,
contrib_payment_attributable NUMBER(15,2) ,
contribution_alloc_pct NUMBER(13,4) ,
net_dollars NUMBER(15,2) ,
disbursements_fee NUMBER(15,2) ,
disbursements_withdrawal NUMBER(15,2) ,
disbursements_termination NUMBER(15,2) ,
disbursements_installment NUMBER(15,2) ,
loan_issues NUMBER(15,2) ,
loan_repayment_interest NUMBER(15,2) ,
loan_repayment_principal NUMBER(15,2) ,
debits_miscellanous NUMBER(15,2) ,
receipts_miscellanous NUMBER(15,2) ,
transfers_in NUMBER(15,2) ,
transfers_out NUMBER(15,2) ,
debits_other NUMBER(15,2) ,
cash_earnings NUMBER(15,2) ,
dividend_earnings NUMBER(15,2) ,
shares_gain_loss_earnings NUMBER(13,4) ,
accrued_dividend_amount NUMBER(15,4) ,
annual_dividend_amount NUMBER(15,4) ,
credited_forfeitures NUMBER(15,2) ,
debited_forfeitures NUMBER(15,2) ,
conversions_in NUMBER(15,2) ,
conversions_out NUMBER(15,2) ,
shares_purchased NUMBER(13,4) ,
shares_receipted NUMBER(13,4) ,
shares_sold NUMBER(13,4) ,
shares_distributed NUMBER(15,2) ,
shares_forfeited NUMBER(15,2) ,
cash_credit_pending NUMBER(15,2) ,
shares_credit_pending NUMBER(15,2) ,
cash_debit_pending NUMBER(15,2) ,
shares_debit_pending NUMBER(15,2) ,
fund_margin_code VARCHAR2(10) ,
account_fund_separate VARCHAR2(10) ,
insurance_premium_paid NUMBER(15,2) ,
trade_date DATE ,
source_cycle_date DATE ,
valuation_date DATE ,
action_code VARCHAR2(1) ,
source_system VARCHAR2(80), 
DELTA_OP_IND varchar2(1)
)
TABLESPACE NEWR_REPOS_DATA
;

-- TABLE: NEWR_REPOS.participant_core_balance
--

GRANT SELECT ON NEWR_REPOS.participant_core_balance_DELTA TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant_core_balance_DELTA TO role_newr_repos_write;

-- TABLE: NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY
-- 

GRANT SELECT ON NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY_DELTA TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.PARTICIPANT_CORE_BALANCE_MONTHLY_DELTA TO role_newr_repos_write;


--NEWR_REPOS.div_sub_transaction_trend;
 drop table NEWR_REPOS.div_sub_transaction_trend;
 drop table NEWR_REPOS.div_sub_transaction_trend_delta;


--NEWR_REPOS.TRANSACTION_TREND 
CREATE TABLE NEWR_REPOS.TRANSACTION_TREND 
(
  CLIENT_ID VARCHAR2(10 BYTE) NOT NULL 
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL
, DIV_SUB_ID VARCHAR2(6 BYTE)  
, SOURCE_CYCLE_DATE DATE 
, TOTAL_BENEFICIARY_SPLITS_COUNT NUMBER(38, 0) 
, TOTAL_CASH_EARNINGS_AMOUNT NUMBER(14, 2) 
, TOTAL_CASH_EARNINGS_COUNT NUMBER(38, 0) 
, TOTAL_DEFAULT_ROLL_DISTRIB_AMOUNT NUMBER(14, 2) 
, TOTAL_DEFAULT_ROLL_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_DEMINIMUS_DISTRIB_AMOUNT NUMBER(14, 2) 
, TOTAL_DEMINIMUS_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_DIVIDEND_PASS_THRU_AMOUNT NUMBER(14, 2) 
, TOTAL_DIVIDEND_PASS_THRU_COUNT NUMBER(38, 0) 
, TOTAL_DIVIDEND_REINVESTMENTS_AMOUNT NUMBER(14, 2) 
, TOTAL_DIVIDEND_REINVESTMENTS_COUNT NUMBER(38, 0) 
, TOTAL_EMP_AFTER_TAX_CONTRI_COUNT NUMBER(38, 0) 
, TOTAL_EMP_BEFORE_TAX_CONTRI_COUNT NUMBER(38, 0) 
, TOTAL_EMPLOYER_CONTRIB_COUNT NUMBER(38, 0) 
, TOTAL_ENROLLMENTS NUMBER(38, 0) 
, TOTAL_FEE_DEDUCTIONS_COUNT NUMBER(38, 0) 
, TOTAL_HARDSHIP_WITHDRAWALS_AMOUNT NUMBER(14, 2) 
, TOTAL_HARDSHIP_WITHDRAWALS_COUNT NUMBER(38, 0) 
, TOTAL_INSRVC_WITHD_NO_ROLL_AMOUNT NUMBER(14, 2) 
, TOTAL_INSRVC_WITHD_NO_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_INSRVC_WITHD_WITH_ROLL_COUNT NUMBER(38, 0)
, TOTAL_INSTALL_DISTRIB_ACH_AMOUNT NUMBER(14, 2) 
, TOTAL_INSTALL_DISTRIB_ACH_COUNT NUMBER(38, 0) 
, TOTAL_INSTALL_DISTRIB_CHECK_AMOUNT NUMBER(14, 2) 
, TOTAL_INSTALL_DISTRIB_CHECK_COUNT NUMBER(38, 0)    
, TOTAL_INSTALLMENTS_SETUP_COUNT NUMBER(38, 0)
, TOTAL_LOAN_DEF_DEEMED_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_ISSUE_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_ISSUE_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_PAYOFF_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_REAMORTIZED_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_REPAYMENTS_COUNT NUMBER(38, 0) 
, TOTAL_QDRO_SPLITS_COUNT NUMBER(38, 0) 
, TOTAL_REBAL_XFER_COUNT NUMBER(38, 0) 
, TOTAL_RMD_AMOUNT NUMBER(14, 2) 
, TOTAL_RMD_COUNT NUMBER(38, 0) 
, TOTAL_ROLLOVER_CONTRIB_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_NO_ROLL_AMOUNT NUMBER(14, 2) 
, TOTAL_TERM_DISTRIB_NO_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_ROLL_NOT_ROLL NUMBER(14, 2) 
, TOTAL_TERM_DISTRIB_ROLL_ROLLED NUMBER(14, 2) 
, TOTAL_UNREAL_EARN_COUNT NUMBER(19, 0) 
, TOTAL_UNREAL_EARN_AMOUNT NUMBER(14, 2) 
, TOTAL_DIV_COUNT NUMBER(19, 0) 
, TOTAL_DIV_AMOUNT NUMBER(14, 2) 
, TOTAL_EARN_BASE_FCT_COUNT NUMBER(19, 0) 
, TOTAL_EARN_BASE_FCT_AMOUNT NUMBER(14, 2) 
, TOTAL_FEE_COUNT NUMBER(38, 0) 
, TOTAL_FEE_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_TO_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_TO_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_FRM_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_FRM_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_REL_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_REL_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_REAMRT_COUNT NUMBER(19, 0) 
, TOTAL_LOAN_REAMRT_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_RAMRT_RT_COUNT NUMBER(19, 0) 
, TOTAL_LOAN_RAMRT_RT_AMOUNT NUMBER(14, 2) 
, TOTAL_ACCORD_INT_COUNT NUMBER(19, 0) 
, TOTAL_ACCORD_INT_AMOUNT NUMBER(14, 2) 
, TOTAL_RTRN_EXCSS_COUNT NUMBER(19, 0) 
, TOTAL_RTRN_EXCSS_AMOUNT NUMBER(14, 2) 
, TOTAL_RTRN_EXCSS_WD_COUNT NUMBER(19, 0) 
, TOTAL_RTRN_EXCSS_WD_AMOUNT NUMBER(14, 2) 
, TOTAL_ENRL_DEM_COUNT NUMBER(19, 0) 
, TOTAL_ENRL_ELEC_COUNT NUMBER(19, 0) 
, TOTAL_DEM_UPDT_COUNT NUMBER(19, 0) 
, TOTAL_INV_ELEC_COUNT NUMBER(19, 0) 
, TOTAL_WITHD_ROLL_NOT_ROLLED_AMOUNT NUMBER(14, 2)
, TOTAL_WITHD_ROLL_ROLLED_AMOUNT NUMBER(14, 2)
, TRANSFORM_HASH_KEY NUMBER(38,0),
CONSTRAINT PK_TRANSACTION_TREND PRIMARY KEY 
(
  CLIENT_ID 
, PLAN_NUMBER 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;


GRANT SELECT ON NEWR_REPOS.transaction_trend TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.transaction_trend TO role_newr_repos_write;



CREATE TABLE NEWR_REPOS.TRANSACTION_TREND_delta
(
  CLIENT_ID VARCHAR2(10 BYTE) NOT NULL 
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL
, DIV_SUB_ID VARCHAR2(6 BYTE)  
, SOURCE_CYCLE_DATE DATE 
, TOTAL_BENEFICIARY_SPLITS_COUNT NUMBER(38, 0) 
, TOTAL_CASH_EARNINGS_AMOUNT NUMBER(14, 2) 
, TOTAL_CASH_EARNINGS_COUNT NUMBER(38, 0) 
, TOTAL_DEFAULT_ROLL_DISTRIB_AMOUNT NUMBER(14, 2) 
, TOTAL_DEFAULT_ROLL_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_DEMINIMUS_DISTRIB_AMOUNT NUMBER(14, 2) 
, TOTAL_DEMINIMUS_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_DIVIDEND_PASS_THRU_AMOUNT NUMBER(14, 2) 
, TOTAL_DIVIDEND_PASS_THRU_COUNT NUMBER(38, 0) 
, TOTAL_DIVIDEND_REINVESTMENTS_AMOUNT NUMBER(14, 2) 
, TOTAL_DIVIDEND_REINVESTMENTS_COUNT NUMBER(38, 0) 
, TOTAL_EMP_AFTER_TAX_CONTRI_COUNT NUMBER(38, 0) 
, TOTAL_EMP_BEFORE_TAX_CONTRI_COUNT NUMBER(38, 0) 
, TOTAL_EMPLOYER_CONTRIB_COUNT NUMBER(38, 0) 
, TOTAL_ENROLLMENTS NUMBER(38, 0) 
, TOTAL_FEE_DEDUCTIONS_COUNT NUMBER(38, 0) 
, TOTAL_HARDSHIP_WITHDRAWALS_AMOUNT NUMBER(14, 2) 
, TOTAL_HARDSHIP_WITHDRAWALS_COUNT NUMBER(38, 0) 
, TOTAL_INSRVC_WITHD_NO_ROLL_AMOUNT NUMBER(14, 2) 
, TOTAL_INSRVC_WITHD_NO_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_INSRVC_WITHD_WITH_ROLL_COUNT NUMBER(38, 0)
, TOTAL_INSTALL_DISTRIB_ACH_AMOUNT NUMBER(14, 2) 
, TOTAL_INSTALL_DISTRIB_ACH_COUNT NUMBER(38, 0) 
, TOTAL_INSTALL_DISTRIB_CHECK_AMOUNT NUMBER(14, 2) 
, TOTAL_INSTALL_DISTRIB_CHECK_COUNT NUMBER(38, 0)    
, TOTAL_INSTALLMENTS_SETUP_COUNT NUMBER(38, 0)
, TOTAL_LOAN_DEF_DEEMED_DISTRIB_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_ISSUE_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_ISSUE_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_PAYOFF_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_REAMORTIZED_COUNT NUMBER(38, 0) 
, TOTAL_LOAN_REPAYMENTS_COUNT NUMBER(38, 0) 
, TOTAL_QDRO_SPLITS_COUNT NUMBER(38, 0) 
, TOTAL_REBAL_XFER_COUNT NUMBER(38, 0) 
, TOTAL_RMD_AMOUNT NUMBER(14, 2) 
, TOTAL_RMD_COUNT NUMBER(38, 0) 
, TOTAL_ROLLOVER_CONTRIB_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_NO_ROLL_AMOUNT NUMBER(14, 2) 
, TOTAL_TERM_DISTRIB_NO_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_ROLL_COUNT NUMBER(38, 0) 
, TOTAL_TERM_DISTRIB_ROLL_NOT_ROLL NUMBER(14, 2) 
, TOTAL_TERM_DISTRIB_ROLL_ROLLED NUMBER(14, 2) 
, TOTAL_UNREAL_EARN_COUNT NUMBER(19, 0) 
, TOTAL_UNREAL_EARN_AMOUNT NUMBER(14, 2) 
, TOTAL_DIV_COUNT NUMBER(19, 0) 
, TOTAL_DIV_AMOUNT NUMBER(14, 2) 
, TOTAL_EARN_BASE_FCT_COUNT NUMBER(19, 0) 
, TOTAL_EARN_BASE_FCT_AMOUNT NUMBER(14, 2) 
, TOTAL_FEE_COUNT NUMBER(38, 0) 
, TOTAL_FEE_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_TO_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_TO_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_FRM_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_FRM_AMOUNT NUMBER(14, 2) 
, TOTAL_INTER_PPT_REL_COUNT NUMBER(19, 0) 
, TOTAL_INTER_PPT_REL_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_REAMRT_COUNT NUMBER(19, 0) 
, TOTAL_LOAN_REAMRT_AMOUNT NUMBER(14, 2) 
, TOTAL_LOAN_RAMRT_RT_COUNT NUMBER(19, 0) 
, TOTAL_LOAN_RAMRT_RT_AMOUNT NUMBER(14, 2) 
, TOTAL_ACCORD_INT_COUNT NUMBER(19, 0) 
, TOTAL_ACCORD_INT_AMOUNT NUMBER(14, 2) 
, TOTAL_RTRN_EXCSS_COUNT NUMBER(19, 0) 
, TOTAL_RTRN_EXCSS_AMOUNT NUMBER(14, 2) 
, TOTAL_RTRN_EXCSS_WD_COUNT NUMBER(19, 0) 
, TOTAL_RTRN_EXCSS_WD_AMOUNT NUMBER(14, 2) 
, TOTAL_ENRL_DEM_COUNT NUMBER(19, 0) 
, TOTAL_ENRL_ELEC_COUNT NUMBER(19, 0) 
, TOTAL_DEM_UPDT_COUNT NUMBER(19, 0) 
, TOTAL_INV_ELEC_COUNT NUMBER(19, 0) 
, TOTAL_WITHD_ROLL_NOT_ROLLED_AMOUNT NUMBER(14, 2)
, TOTAL_WITHD_ROLL_ROLLED_AMOUNT NUMBER(14, 2)
, TRANSFORM_HASH_KEY NUMBER(38,0)
, DELTA_OP_IND VARCHAR(1)
)
TABLESPACE NEWR_REPOS_DATA
;


GRANT SELECT ON NEWR_REPOS.transaction_trend_delta TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.transaction_trend_delta TO role_newr_repos_write;




drop table NEWR_REPOS.div_sub_part_status_trend;
drop table NEWR_REPOS.div_sub_part_status_trend_delta;


CREATE TABLE NEWR_REPOS.PARTICIPANT_STATUS_TREND 
(
  CLIENT_ID VARCHAR2(10 BYTE) NOT NULL 
, PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, DIV_SUB_ID VARCHAR2(6 BYTE) 
, SOURCE_CYCLE_DATE DATE NOT NULL 
, ACTIVE_CONTRIBUTING_COUNT VARCHAR2(10 BYTE) 
, ACTIVE_CONTRIBUTING_TOTAL_BALANCE NUMBER(14, 2) 
, ACTIVE_NOT_CONTRIBUTING_COUNT VARCHAR2(10 BYTE) 
, ACTIVE_NOT_CONTRIBUTE_TOTAL_AMOUNT NUMBER(14, 2) 
, CATCHUP_ELIGIBLE_COUNT VARCHAR2(10 BYTE) 
, CATCHUP_ELIGIBLE_TOTAL_AMOUNT NUMBER(14, 2) 
, CATCHUP_PARTICIPATING_COUNT VARCHAR2(10 BYTE) 
, CATCHUP_PART_TOTAL_AMOUNT NUMBER(14, 2) 
, ELIG_NOT_PART_NOT_BALANCE_COUNT VARCHAR2(10 BYTE) 
, ELIG_NOT_PART_BALANCE_COUNT VARCHAR2(10 BYTE) 
, ELIG_NOT_PART_TOTAL_AMOUNT NUMBER(14, 2) 
, INELIGIBLE_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, INELIGIBLE_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, OMNI_STATUS_CODE_01_COUNT VARCHAR2(10 BYTE) 
, OMNI_STATUS_CODE_01_TOTAL_AMOUNT NUMBER(14, 2) 
, OMNI_STATUS_CODE_05_COUNT VARCHAR2(10 BYTE) 
, OMNI_STATUS_CODE_05_TOTAL_BAL NUMBER(14, 2) 
, PART_WITH_BALANCE_AVERAGE_AMOUNT NUMBER(14, 2) 
, PART_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, PARTICIPANTS_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, SUSPENDED_NO_BALANCE_COUNT VARCHAR2(10 BYTE) 
, SUSPENDED_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, SUSPENDED_WITH_BAL_TOTAL_BAL NUMBER(14, 2) 
, TERMINATED_NO_BALANCE_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_REC_INSTALL_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_REC_INSTALL_TOTAL_AMOUNT NUMBER(14, 2) 
, TERMINATED_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, SOURCE_SYSTEM VARCHAR2(80 BYTE) ,
CONSTRAINT PK_DIV_SUB_PART_STATUS_TREND PRIMARY KEY 
(
  CLIENT_ID 
, SOURCE_CYCLE_DATE 
, PLAN_NUMBER 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;


GRANT SELECT ON NEWR_REPOS.participant_status_trend TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant_status_trend TO role_newr_repos_write;




--participant_status_trend_delta

CREATE TABLE NEWR_REPOS.PARTICIPANT_STATUS_TREND_DELTA
(
  CLIENT_ID VARCHAR2(10 BYTE)
, PLAN_NUMBER VARCHAR2(25 BYTE)  
, DIV_SUB_ID VARCHAR2(6 BYTE) 
, SOURCE_CYCLE_DATE DATE  
, ACTIVE_CONTRIBUTING_COUNT VARCHAR2(10 BYTE) 
, ACTIVE_CONTRIBUTING_TOTAL_BALANCE NUMBER(14, 2) 
, ACTIVE_NOT_CONTRIBUTING_COUNT VARCHAR2(10 BYTE) 
, ACTIVE_NOT_CONTRIBUTE_TOTAL_AMOUNT NUMBER(14, 2) 
, CATCHUP_ELIGIBLE_COUNT VARCHAR2(10 BYTE) 
, CATCHUP_ELIGIBLE_TOTAL_AMOUNT NUMBER(14, 2) 
, CATCHUP_PARTICIPATING_COUNT VARCHAR2(10 BYTE) 
, CATCHUP_PART_TOTAL_AMOUNT NUMBER(14, 2) 
, ELIG_NOT_PART_NOT_BALANCE_COUNT VARCHAR2(10 BYTE) 
, ELIG_NOT_PART_BALANCE_COUNT VARCHAR2(10 BYTE) 
, ELIG_NOT_PART_TOTAL_AMOUNT NUMBER(14, 2) 
, INELIGIBLE_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, INELIGIBLE_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, OMNI_STATUS_CODE_01_COUNT VARCHAR2(10 BYTE) 
, OMNI_STATUS_CODE_01_TOTAL_AMOUNT NUMBER(14, 2) 
, OMNI_STATUS_CODE_05_COUNT VARCHAR2(10 BYTE) 
, OMNI_STATUS_CODE_05_TOTAL_BAL NUMBER(14, 2) 
, PART_WITH_BALANCE_AVERAGE_AMOUNT NUMBER(14, 2) 
, PART_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, PARTICIPANTS_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, SUSPENDED_NO_BALANCE_COUNT VARCHAR2(10 BYTE) 
, SUSPENDED_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, SUSPENDED_WITH_BAL_TOTAL_BAL NUMBER(14, 2) 
, TERMINATED_NO_BALANCE_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_REC_INSTALL_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_REC_INSTALL_TOTAL_AMOUNT NUMBER(14, 2) 
, TERMINATED_WITH_BALANCE_COUNT VARCHAR2(10 BYTE) 
, TERMINATED_WITH_BALANCE_TOTAL_AMOUNT NUMBER(14, 2) 
, SOURCE_SYSTEM VARCHAR2(80 BYTE) 
, DELTA_OP_IND VARCHAR(1)
)
TABLESPACE NEWR_REPOS_DATA
;


GRANT SELECT ON NEWR_REPOS.participant_status_trend_delta TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.participant_status_trend_delta TO role_newr_repos_write;
